# fly.toml app configuration file generated for gitrip-mvp on 2026-02-15T13:04:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gitrip'
primary_region = 'lhr'

[build]

[env]
  DATABASE_PATH = '/data/gitrip.db'
  PORT = '8080'

[[mounts]]
  source = 'gitrip_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
